/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth.projects.index'
import { Route as AuthPostsIndexRouteImport } from './routes/_auth.posts.index'
import { Route as AuthExperiencesIndexRouteImport } from './routes/_auth.experiences.index'
import { Route as AuthProjectsNewRouteImport } from './routes/_auth.projects.new'
import { Route as AuthPostsNewRouteImport } from './routes/_auth.posts.new'
import { Route as AuthExperiencesNewRouteImport } from './routes/_auth.experiences.new'
import { Route as AuthProjectsIdEditRouteImport } from './routes/_auth.projects.$id.edit'
import { Route as AuthPostsIdEditRouteImport } from './routes/_auth.posts.$id.edit'
import { Route as AuthExperiencesIdEditRouteImport } from './routes/_auth.experiences.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsIndexRoute = AuthPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExperiencesIndexRoute = AuthExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsNewRoute = AuthProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsNewRoute = AuthPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExperiencesNewRoute = AuthExperiencesNewRouteImport.update({
  id: '/experiences/new',
  path: '/experiences/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIdEditRoute = AuthProjectsIdEditRouteImport.update({
  id: '/projects/$id/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsIdEditRoute = AuthPostsIdEditRouteImport.update({
  id: '/posts/$id/edit',
  path: '/posts/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExperiencesIdEditRoute = AuthExperiencesIdEditRouteImport.update({
  id: '/experiences/$id/edit',
  path: '/experiences/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/login/callback': typeof LoginCallbackRoute
  '/experiences/new': typeof AuthExperiencesNewRoute
  '/posts/new': typeof AuthPostsNewRoute
  '/projects/new': typeof AuthProjectsNewRoute
  '/experiences/': typeof AuthExperiencesIndexRoute
  '/posts/': typeof AuthPostsIndexRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/experiences/$id/edit': typeof AuthExperiencesIdEditRoute
  '/posts/$id/edit': typeof AuthPostsIdEditRoute
  '/projects/$id/edit': typeof AuthProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/login/callback': typeof LoginCallbackRoute
  '/experiences/new': typeof AuthExperiencesNewRoute
  '/posts/new': typeof AuthPostsNewRoute
  '/projects/new': typeof AuthProjectsNewRoute
  '/experiences': typeof AuthExperiencesIndexRoute
  '/posts': typeof AuthPostsIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/experiences/$id/edit': typeof AuthExperiencesIdEditRoute
  '/posts/$id/edit': typeof AuthPostsIdEditRoute
  '/projects/$id/edit': typeof AuthProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/login/callback': typeof LoginCallbackRoute
  '/_auth/experiences/new': typeof AuthExperiencesNewRoute
  '/_auth/posts/new': typeof AuthPostsNewRoute
  '/_auth/projects/new': typeof AuthProjectsNewRoute
  '/_auth/experiences/': typeof AuthExperiencesIndexRoute
  '/_auth/posts/': typeof AuthPostsIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/experiences/$id/edit': typeof AuthExperiencesIdEditRoute
  '/_auth/posts/$id/edit': typeof AuthPostsIdEditRoute
  '/_auth/projects/$id/edit': typeof AuthProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/login/callback'
    | '/experiences/new'
    | '/posts/new'
    | '/projects/new'
    | '/experiences/'
    | '/posts/'
    | '/projects/'
    | '/experiences/$id/edit'
    | '/posts/$id/edit'
    | '/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/login/callback'
    | '/experiences/new'
    | '/posts/new'
    | '/projects/new'
    | '/experiences'
    | '/posts'
    | '/projects'
    | '/experiences/$id/edit'
    | '/posts/$id/edit'
    | '/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/login/callback'
    | '/_auth/experiences/new'
    | '/_auth/posts/new'
    | '/_auth/projects/new'
    | '/_auth/experiences/'
    | '/_auth/posts/'
    | '/_auth/projects/'
    | '/_auth/experiences/$id/edit'
    | '/_auth/posts/$id/edit'
    | '/_auth/projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/': {
      id: '/_auth/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthPostsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/experiences/': {
      id: '/_auth/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof AuthExperiencesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/new': {
      id: '/_auth/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthProjectsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/new': {
      id: '/_auth/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthPostsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/experiences/new': {
      id: '/_auth/experiences/new'
      path: '/experiences/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof AuthExperiencesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$id/edit': {
      id: '/_auth/projects/$id/edit'
      path: '/projects/$id/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof AuthProjectsIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/$id/edit': {
      id: '/_auth/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/posts/$id/edit'
      preLoaderRoute: typeof AuthPostsIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/experiences/$id/edit': {
      id: '/_auth/experiences/$id/edit'
      path: '/experiences/$id/edit'
      fullPath: '/experiences/$id/edit'
      preLoaderRoute: typeof AuthExperiencesIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthExperiencesNewRoute: typeof AuthExperiencesNewRoute
  AuthPostsNewRoute: typeof AuthPostsNewRoute
  AuthProjectsNewRoute: typeof AuthProjectsNewRoute
  AuthExperiencesIndexRoute: typeof AuthExperiencesIndexRoute
  AuthPostsIndexRoute: typeof AuthPostsIndexRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthExperiencesIdEditRoute: typeof AuthExperiencesIdEditRoute
  AuthPostsIdEditRoute: typeof AuthPostsIdEditRoute
  AuthProjectsIdEditRoute: typeof AuthProjectsIdEditRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthExperiencesNewRoute: AuthExperiencesNewRoute,
  AuthPostsNewRoute: AuthPostsNewRoute,
  AuthProjectsNewRoute: AuthProjectsNewRoute,
  AuthExperiencesIndexRoute: AuthExperiencesIndexRoute,
  AuthPostsIndexRoute: AuthPostsIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthExperiencesIdEditRoute: AuthExperiencesIdEditRoute,
  AuthPostsIdEditRoute: AuthPostsIdEditRoute,
  AuthProjectsIdEditRoute: AuthProjectsIdEditRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
